// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/event/can_partner_access_engagement_id/{partnerId}/{engagementId}/{programTypeGuid}": {
            "get": {
                "description": "Check if a partner can access an engagement ID by partner ID, engagement ID, and program type GUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Check if a partner can access an engagement ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "partnerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Engagement ID",
                        "name": "engagementId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Program Type GUID",
                        "name": "programTypeGuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/event/can_partner_access_event_registration_batch_id/{partnerId}/{eventBatchId}/{programTypeGuid}": {
            "get": {
                "description": "Check if a partner can access an event registration batch ID by partner ID, event batch ID, and program type GUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Check if a partner can access an event registration batch ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "partnerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event Batch ID",
                        "name": "eventBatchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Program Type GUID",
                        "name": "programTypeGuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/event/get_proposed_event/{eventRegistrationBatchId}": {
            "get": {
                "description": "Get proposed event details by event registration batch ID and program type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get proposed event details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Registration Batch ID",
                        "name": "eventRegistrationBatchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Program Type",
                        "name": "programType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/event/is_on_event_access_list/{partnerId}": {
            "get": {
                "description": "Check if an event is on the access list by partner ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Check if an event is on the access list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "partnerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
